### model
model_name_or_path: /root/autodl-tmp/models/qwen2.5-0.5b
resize_vocab: True

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /root/autodl-tmp/train_config/ds_z3_config.json

### dataset
dataset: chatharuhi54k-train
# dataset: llama-7b-math-merge-data
dataset_dir: /root/autodl-tmp/LLaMA-Factory/data
template: qwen-roleplay
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2-1.5-sft-roleplay/
logging_steps: 100
save_steps: 4100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
